/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    input pulseA,
    input pulseB,
    input pulseC,
    input pulseD
  );
  
  
  
  reg rst;
  
  reg ctr_rst;
  
  localparam CLKSPEED = 28'h80befc0;
  
  wire [1-1:0] M_fast_CLK_OUT1;
  medclk fast (
    .CLK_IN1(clk),
    .CLK_OUT1(M_fast_CLK_OUT1)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(M_fast_CLK_OUT1),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  reg [719:0] M_counts_d, M_counts_q = 1'h0;
  wire [1-1:0] M_avr_spi_miso;
  wire [4-1:0] M_avr_spi_channel;
  wire [1-1:0] M_avr_tx;
  wire [1-1:0] M_avr_new_sample;
  wire [10-1:0] M_avr_sample;
  wire [4-1:0] M_avr_sample_channel;
  wire [1-1:0] M_avr_tx_busy;
  wire [8-1:0] M_avr_rx_data;
  wire [1-1:0] M_avr_new_rx_data;
  reg [1-1:0] M_avr_cclk;
  reg [1-1:0] M_avr_spi_mosi;
  reg [1-1:0] M_avr_spi_sck;
  reg [1-1:0] M_avr_spi_ss;
  reg [1-1:0] M_avr_rx;
  reg [4-1:0] M_avr_channel;
  reg [8-1:0] M_avr_tx_data;
  reg [1-1:0] M_avr_new_tx_data;
  reg [1-1:0] M_avr_tx_block;
  avr_interface_2 avr (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .cclk(M_avr_cclk),
    .spi_mosi(M_avr_spi_mosi),
    .spi_sck(M_avr_spi_sck),
    .spi_ss(M_avr_spi_ss),
    .rx(M_avr_rx),
    .channel(M_avr_channel),
    .tx_data(M_avr_tx_data),
    .new_tx_data(M_avr_new_tx_data),
    .tx_block(M_avr_tx_block),
    .spi_miso(M_avr_spi_miso),
    .spi_channel(M_avr_spi_channel),
    .tx(M_avr_tx),
    .new_sample(M_avr_new_sample),
    .sample(M_avr_sample),
    .sample_channel(M_avr_sample_channel),
    .tx_busy(M_avr_tx_busy),
    .rx_data(M_avr_rx_data),
    .new_rx_data(M_avr_new_rx_data)
  );
  wire [1-1:0] M_tmr_maxval;
  wire [24-1:0] M_tmr_value;
  timer_3 tmr (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .maxval(M_tmr_maxval),
    .value(M_tmr_value)
  );
  reg [7:0] M_pins_d, M_pins_q = 1'h0;
  reg [7:0] M_pulse_length_d, M_pulse_length_q = 1'h0;
  reg [719:0] M_count_store_d, M_count_store_q = 1'h0;
  localparam COUNT_state = 1'd0;
  localparam BLIND_state = 1'd1;
  
  reg M_state_d, M_state_q = COUNT_state;
  wire [1-1:0] M_buff_new_tx_out;
  wire [8-1:0] M_buff_tx_data_out;
  reg [1-1:0] M_buff_drdy;
  reg [1-1:0] M_buff_tx_busy_out;
  serialbuffer_4 buff (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .count_store(M_count_store_q),
    .drdy(M_buff_drdy),
    .tx_busy_out(M_buff_tx_busy_out),
    .new_tx_out(M_buff_new_tx_out),
    .tx_data_out(M_buff_tx_data_out)
  );
  wire [1-1:0] M_xdupA_out;
  reg [1-1:0] M_xdupA_pulse;
  duplicator_5 xdupA (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pulse(M_xdupA_pulse),
    .out(M_xdupA_out)
  );
  wire [1-1:0] M_xdupB_out;
  reg [1-1:0] M_xdupB_pulse;
  duplicator_5 xdupB (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pulse(M_xdupB_pulse),
    .out(M_xdupB_out)
  );
  wire [1-1:0] M_xdupC_out;
  reg [1-1:0] M_xdupC_pulse;
  duplicator_5 xdupC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pulse(M_xdupC_pulse),
    .out(M_xdupC_out)
  );
  wire [1-1:0] M_xdupD_out;
  reg [1-1:0] M_xdupD_pulse;
  duplicator_5 xdupD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pulse(M_xdupD_pulse),
    .out(M_xdupD_out)
  );
  wire [1-1:0] M_ydupA_out;
  reg [1-1:0] M_ydupA_pulse;
  duplicator_5 ydupA (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pulse(M_ydupA_pulse),
    .out(M_ydupA_out)
  );
  wire [1-1:0] M_ydupB_out;
  reg [1-1:0] M_ydupB_pulse;
  duplicator_5 ydupB (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pulse(M_ydupB_pulse),
    .out(M_ydupB_out)
  );
  wire [1-1:0] M_ydupC_out;
  reg [1-1:0] M_ydupC_pulse;
  duplicator_5 ydupC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pulse(M_ydupC_pulse),
    .out(M_ydupC_out)
  );
  wire [1-1:0] M_ydupD_out;
  reg [1-1:0] M_ydupD_pulse;
  duplicator_5 ydupD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pulse(M_ydupD_pulse),
    .out(M_ydupD_out)
  );
  wire [1-1:0] M_xcompA_incr;
  reg [4-1:0] M_xcompA_pins;
  comparator_13 xcompA (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompA_pins),
    .incr(M_xcompA_incr)
  );
  wire [1-1:0] M_xcompB_incr;
  reg [4-1:0] M_xcompB_pins;
  comparator_13 xcompB (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompB_pins),
    .incr(M_xcompB_incr)
  );
  wire [1-1:0] M_xcompC_incr;
  reg [4-1:0] M_xcompC_pins;
  comparator_13 xcompC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompC_pins),
    .incr(M_xcompC_incr)
  );
  wire [1-1:0] M_xcompD_incr;
  reg [4-1:0] M_xcompD_pins;
  comparator_13 xcompD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompD_pins),
    .incr(M_xcompD_incr)
  );
  wire [1-1:0] M_xcompAB_incr;
  reg [4-1:0] M_xcompAB_pins;
  comparator_13 xcompAB (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompAB_pins),
    .incr(M_xcompAB_incr)
  );
  wire [1-1:0] M_xcompAC_incr;
  reg [4-1:0] M_xcompAC_pins;
  comparator_13 xcompAC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompAC_pins),
    .incr(M_xcompAC_incr)
  );
  wire [1-1:0] M_xcompAD_incr;
  reg [4-1:0] M_xcompAD_pins;
  comparator_13 xcompAD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompAD_pins),
    .incr(M_xcompAD_incr)
  );
  wire [1-1:0] M_xcompBC_incr;
  reg [4-1:0] M_xcompBC_pins;
  comparator_13 xcompBC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompBC_pins),
    .incr(M_xcompBC_incr)
  );
  wire [1-1:0] M_xcompBD_incr;
  reg [4-1:0] M_xcompBD_pins;
  comparator_13 xcompBD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompBD_pins),
    .incr(M_xcompBD_incr)
  );
  wire [1-1:0] M_xcompCD_incr;
  reg [4-1:0] M_xcompCD_pins;
  comparator_13 xcompCD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompCD_pins),
    .incr(M_xcompCD_incr)
  );
  wire [1-1:0] M_xcompABC_incr;
  reg [4-1:0] M_xcompABC_pins;
  comparator_13 xcompABC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompABC_pins),
    .incr(M_xcompABC_incr)
  );
  wire [1-1:0] M_xcompABD_incr;
  reg [4-1:0] M_xcompABD_pins;
  comparator_13 xcompABD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompABD_pins),
    .incr(M_xcompABD_incr)
  );
  wire [1-1:0] M_xcompACD_incr;
  reg [4-1:0] M_xcompACD_pins;
  comparator_13 xcompACD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompACD_pins),
    .incr(M_xcompACD_incr)
  );
  wire [1-1:0] M_xcompBCD_incr;
  reg [4-1:0] M_xcompBCD_pins;
  comparator_13 xcompBCD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompBCD_pins),
    .incr(M_xcompBCD_incr)
  );
  wire [1-1:0] M_xcompABCD_incr;
  reg [4-1:0] M_xcompABCD_pins;
  comparator_13 xcompABCD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[0+3-:4]),
    .pins(M_xcompABCD_pins),
    .incr(M_xcompABCD_incr)
  );
  wire [1-1:0] M_ycompA_incr;
  reg [4-1:0] M_ycompA_pins;
  comparator_13 ycompA (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompA_pins),
    .incr(M_ycompA_incr)
  );
  wire [1-1:0] M_ycompB_incr;
  reg [4-1:0] M_ycompB_pins;
  comparator_13 ycompB (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompB_pins),
    .incr(M_ycompB_incr)
  );
  wire [1-1:0] M_ycompC_incr;
  reg [4-1:0] M_ycompC_pins;
  comparator_13 ycompC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompC_pins),
    .incr(M_ycompC_incr)
  );
  wire [1-1:0] M_ycompD_incr;
  reg [4-1:0] M_ycompD_pins;
  comparator_13 ycompD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompD_pins),
    .incr(M_ycompD_incr)
  );
  wire [1-1:0] M_ycompAB_incr;
  reg [4-1:0] M_ycompAB_pins;
  comparator_13 ycompAB (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompAB_pins),
    .incr(M_ycompAB_incr)
  );
  wire [1-1:0] M_ycompAC_incr;
  reg [4-1:0] M_ycompAC_pins;
  comparator_13 ycompAC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompAC_pins),
    .incr(M_ycompAC_incr)
  );
  wire [1-1:0] M_ycompAD_incr;
  reg [4-1:0] M_ycompAD_pins;
  comparator_13 ycompAD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompAD_pins),
    .incr(M_ycompAD_incr)
  );
  wire [1-1:0] M_ycompBC_incr;
  reg [4-1:0] M_ycompBC_pins;
  comparator_13 ycompBC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompBC_pins),
    .incr(M_ycompBC_incr)
  );
  wire [1-1:0] M_ycompBD_incr;
  reg [4-1:0] M_ycompBD_pins;
  comparator_13 ycompBD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompBD_pins),
    .incr(M_ycompBD_incr)
  );
  wire [1-1:0] M_ycompCD_incr;
  reg [4-1:0] M_ycompCD_pins;
  comparator_13 ycompCD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompCD_pins),
    .incr(M_ycompCD_incr)
  );
  wire [1-1:0] M_ycompABC_incr;
  reg [4-1:0] M_ycompABC_pins;
  comparator_13 ycompABC (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompABC_pins),
    .incr(M_ycompABC_incr)
  );
  wire [1-1:0] M_ycompABD_incr;
  reg [4-1:0] M_ycompABD_pins;
  comparator_13 ycompABD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompABD_pins),
    .incr(M_ycompABD_incr)
  );
  wire [1-1:0] M_ycompACD_incr;
  reg [4-1:0] M_ycompACD_pins;
  comparator_13 ycompACD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompACD_pins),
    .incr(M_ycompACD_incr)
  );
  wire [1-1:0] M_ycompBCD_incr;
  reg [4-1:0] M_ycompBCD_pins;
  comparator_13 ycompBCD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompBCD_pins),
    .incr(M_ycompBCD_incr)
  );
  wire [1-1:0] M_ycompABCD_incr;
  reg [4-1:0] M_ycompABCD_pins;
  comparator_13 ycompABCD (
    .clk(M_fast_CLK_OUT1),
    .rst(rst),
    .length(M_pulse_length_q[4+3-:4]),
    .pins(M_ycompABCD_pins),
    .incr(M_ycompABCD_incr)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_pins_d = M_pins_q;
    M_count_store_d = M_count_store_q;
    M_counts_d = M_counts_q;
    M_pulse_length_d = M_pulse_length_q;
    
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    M_buff_drdy = 1'h0;
    led = M_counts_q[0+0+7-:8];
    ctr_rst = 1'h0;
    M_xdupA_pulse = pulseA;
    M_xdupB_pulse = pulseB;
    M_xdupC_pulse = pulseC;
    M_xdupD_pulse = pulseD;
    M_ydupA_pulse = pulseA;
    M_ydupB_pulse = pulseB;
    M_ydupC_pulse = pulseC;
    M_ydupD_pulse = pulseD;
    M_pins_d[0+0+0-:1] = M_xdupA_out;
    M_pins_d[0+1+0-:1] = M_xdupB_out;
    M_pins_d[0+2+0-:1] = M_xdupC_out;
    M_pins_d[0+3+0-:1] = M_xdupD_out;
    M_pins_d[4+0+0-:1] = M_ydupA_out;
    M_pins_d[4+1+0-:1] = M_ydupB_out;
    M_pins_d[4+2+0-:1] = M_ydupC_out;
    M_pins_d[4+3+0-:1] = M_ydupD_out;
    M_xcompA_pins = (M_pins_q[0+3-:4] | 4'he);
    M_xcompB_pins = (M_pins_q[0+3-:4] | 4'hd);
    M_xcompC_pins = (M_pins_q[0+3-:4] | 4'hb);
    M_xcompD_pins = (M_pins_q[0+3-:4] | 4'h7);
    M_xcompAB_pins = (M_pins_q[0+3-:4] | 4'hc);
    M_xcompAC_pins = (M_pins_q[0+3-:4] | 4'ha);
    M_xcompAD_pins = (M_pins_q[0+3-:4] | 4'h6);
    M_xcompBC_pins = (M_pins_q[0+3-:4] | 4'h9);
    M_xcompBD_pins = (M_pins_q[0+3-:4] | 4'h5);
    M_xcompCD_pins = (M_pins_q[0+3-:4] | 4'h3);
    M_xcompABC_pins = (M_pins_q[0+3-:4] | 4'h8);
    M_xcompABD_pins = (M_pins_q[0+3-:4] | 4'h4);
    M_xcompACD_pins = (M_pins_q[0+3-:4] | 4'h2);
    M_xcompBCD_pins = (M_pins_q[0+3-:4] | 4'h1);
    M_xcompABCD_pins = (M_pins_q[0+3-:4] | 4'h0);
    M_ycompA_pins = (M_pins_q[4+3-:4] | 4'he);
    M_ycompB_pins = (M_pins_q[4+3-:4] | 4'hd);
    M_ycompC_pins = (M_pins_q[4+3-:4] | 4'hb);
    M_ycompD_pins = (M_pins_q[4+3-:4] | 4'h7);
    M_ycompAB_pins = (M_pins_q[4+3-:4] | 4'hc);
    M_ycompAC_pins = (M_pins_q[4+3-:4] | 4'ha);
    M_ycompAD_pins = (M_pins_q[4+3-:4] | 4'h6);
    M_ycompBC_pins = (M_pins_q[4+3-:4] | 4'h9);
    M_ycompBD_pins = (M_pins_q[4+3-:4] | 4'h5);
    M_ycompCD_pins = (M_pins_q[4+3-:4] | 4'h3);
    M_ycompABC_pins = (M_pins_q[4+3-:4] | 4'h8);
    M_ycompABD_pins = (M_pins_q[4+3-:4] | 4'h4);
    M_ycompACD_pins = (M_pins_q[4+3-:4] | 4'h2);
    M_ycompBCD_pins = (M_pins_q[4+3-:4] | 4'h1);
    M_ycompABCD_pins = (M_pins_q[4+3-:4] | 4'h0);
    M_avr_cclk = cclk;
    M_avr_spi_ss = spi_ss;
    M_avr_spi_mosi = spi_mosi;
    M_avr_spi_sck = spi_sck;
    M_avr_rx = avr_tx;
    M_avr_channel = 4'hf;
    M_avr_tx_block = avr_rx_busy;
    spi_miso = M_avr_spi_miso;
    spi_channel = M_avr_spi_channel;
    avr_rx = M_avr_tx;
    M_avr_tx_data = M_buff_tx_data_out;
    M_avr_new_tx_data = M_buff_new_tx_out;
    M_buff_tx_busy_out = M_avr_tx_busy;
    M_buff_drdy = 1'h0;
    if (M_avr_new_rx_data) begin
      M_pulse_length_d[0+3-:4] = M_avr_rx_data[0+3-:4];
      M_pulse_length_d[4+3-:4] = M_avr_rx_data[4+3-:4];
    end
    
    case (M_state_q)
      COUNT_state: begin
        if (M_xcompA_incr) begin
          M_counts_d[0+23-:24] = M_counts_q[0+23-:24] + 1'h1;
        end
        if (M_xcompB_incr) begin
          M_counts_d[24+23-:24] = M_counts_q[24+23-:24] + 1'h1;
        end
        if (M_xcompC_incr) begin
          M_counts_d[48+23-:24] = M_counts_q[48+23-:24] + 1'h1;
        end
        if (M_xcompD_incr) begin
          M_counts_d[72+23-:24] = M_counts_q[72+23-:24] + 1'h1;
        end
        if (M_xcompAB_incr) begin
          M_counts_d[96+23-:24] = M_counts_q[96+23-:24] + 1'h1;
        end
        if (M_xcompAC_incr) begin
          M_counts_d[120+23-:24] = M_counts_q[120+23-:24] + 1'h1;
        end
        if (M_xcompAD_incr) begin
          M_counts_d[144+23-:24] = M_counts_q[144+23-:24] + 1'h1;
        end
        if (M_xcompBC_incr) begin
          M_counts_d[168+23-:24] = M_counts_q[168+23-:24] + 1'h1;
        end
        if (M_xcompBD_incr) begin
          M_counts_d[192+23-:24] = M_counts_q[192+23-:24] + 1'h1;
        end
        if (M_xcompCD_incr) begin
          M_counts_d[216+23-:24] = M_counts_q[216+23-:24] + 1'h1;
        end
        if (M_xcompABC_incr) begin
          M_counts_d[240+23-:24] = M_counts_q[240+23-:24] + 1'h1;
        end
        if (M_xcompABD_incr) begin
          M_counts_d[264+23-:24] = M_counts_q[264+23-:24] + 1'h1;
        end
        if (M_xcompACD_incr) begin
          M_counts_d[288+23-:24] = M_counts_q[288+23-:24] + 1'h1;
        end
        if (M_xcompBCD_incr) begin
          M_counts_d[312+23-:24] = M_counts_q[312+23-:24] + 1'h1;
        end
        if (M_xcompABCD_incr) begin
          M_counts_d[336+23-:24] = M_counts_q[336+23-:24] + 1'h1;
        end
        if (M_ycompA_incr) begin
          M_counts_d[360+23-:24] = M_counts_q[360+23-:24] + 1'h1;
        end
        if (M_ycompB_incr) begin
          M_counts_d[384+23-:24] = M_counts_q[384+23-:24] + 1'h1;
        end
        if (M_ycompC_incr) begin
          M_counts_d[408+23-:24] = M_counts_q[408+23-:24] + 1'h1;
        end
        if (M_ycompD_incr) begin
          M_counts_d[432+23-:24] = M_counts_q[432+23-:24] + 1'h1;
        end
        if (M_ycompAB_incr) begin
          M_counts_d[456+23-:24] = M_counts_q[456+23-:24] + 1'h1;
        end
        if (M_ycompAC_incr) begin
          M_counts_d[480+23-:24] = M_counts_q[480+23-:24] + 1'h1;
        end
        if (M_ycompAD_incr) begin
          M_counts_d[504+23-:24] = M_counts_q[504+23-:24] + 1'h1;
        end
        if (M_ycompBC_incr) begin
          M_counts_d[528+23-:24] = M_counts_q[528+23-:24] + 1'h1;
        end
        if (M_ycompBD_incr) begin
          M_counts_d[552+23-:24] = M_counts_q[552+23-:24] + 1'h1;
        end
        if (M_ycompCD_incr) begin
          M_counts_d[576+23-:24] = M_counts_q[576+23-:24] + 1'h1;
        end
        if (M_ycompABC_incr) begin
          M_counts_d[600+23-:24] = M_counts_q[600+23-:24] + 1'h1;
        end
        if (M_ycompABD_incr) begin
          M_counts_d[624+23-:24] = M_counts_q[624+23-:24] + 1'h1;
        end
        if (M_ycompACD_incr) begin
          M_counts_d[648+23-:24] = M_counts_q[648+23-:24] + 1'h1;
        end
        if (M_ycompBCD_incr) begin
          M_counts_d[672+23-:24] = M_counts_q[672+23-:24] + 1'h1;
        end
        if (M_ycompABCD_incr) begin
          M_counts_d[696+23-:24] = M_counts_q[696+23-:24] + 1'h1;
        end
        if (M_tmr_maxval) begin
          M_state_d = BLIND_state;
        end
      end
      BLIND_state: begin
        M_count_store_d = M_counts_q;
        ctr_rst = 1'h1;
        M_buff_drdy = 1'h1;
        M_state_d = COUNT_state;
      end
    endcase
  end
  
  always @(posedge M_fast_CLK_OUT1) begin
    if (ctr_rst == 1'b1) begin
      M_counts_q <= 1'h0;
    end else begin
      M_counts_q <= M_counts_d;
    end
    
    if (rst == 1'b1) begin
      M_pins_q <= 1'h0;
      M_pulse_length_q <= 1'h0;
      M_count_store_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_pins_q <= M_pins_d;
      M_pulse_length_q <= M_pulse_length_d;
      M_count_store_q <= M_count_store_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
