/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = $clog2(CLKSPEED/2)
     DIV = 0
     TOP = (CLKSPEED/2)-1
     UP = 1
*/
module timer_4 (
    input clk,
    input rst,
    output reg maxval,
    output reg [26:0] value
  );
  
  localparam SIZE = 5'h1b;
  localparam DIV = 1'h0;
  localparam TOP = 29'h047868bf;
  localparam UP = 1'h1;
  
  
  reg [26:0] M_ctr_d, M_ctr_q = 1'h0;
  
  localparam MAX_VALUE = 29'h047868bf;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q[0+26-:27];
    maxval = 1'h0;
    if (1'h1) begin
      M_ctr_d = M_ctr_q + 1'h1;
      if (1'h1 && M_ctr_q == 29'h047868bf) begin
        M_ctr_d = 1'h0;
        maxval = 1'h1;
      end
    end else begin
      M_ctr_d = M_ctr_q - 1'h1;
      if (1'h1 && M_ctr_q == 1'h0) begin
        M_ctr_d = 29'h047868bf;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
