/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_13 (
    input clk,
    input rst,
    input [3:0] pins,
    input [3:0] length,
    output reg incr
  );
  
  
  
  
  localparam COMPARE_state = 1'd0;
  localparam SLEEP_state = 1'd1;
  
  reg M_state_d, M_state_q = COMPARE_state;
  
  reg [3:0] M_ctr_d, M_ctr_q = 1'h0;
  
  always @* begin
    M_state_d = M_state_q;
    M_ctr_d = M_ctr_q;
    
    incr = 1'h0;
    
    case (M_state_q)
      COMPARE_state: begin
        if ((&pins)) begin
          incr = 1'h1;
          M_state_d = SLEEP_state;
        end
      end
      SLEEP_state: begin
        if (M_ctr_q == length - 1'h1) begin
          M_ctr_d = 1'h0;
          M_state_d = COMPARE_state;
        end else begin
          M_ctr_d = M_ctr_q + 1'h1;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
